sudo: required

before_install:
- sudo apt-get install zip
- sudo apt install ccache
- git clone --recursive https://github.com/TheRagingBeast/TheRagingBeast-kernel-Moto-C-plus -b mod ~/trb
- git clone --recursive https://github.com/varunhardgamer/SaberMod_GCC_4.8.2_arm-eabi ~/trb/tc
- git clone --recursive https://github.com/varunhardgamer/LazyFlasher ~/trb/lf
script:
- cd ~/trb
- chmod a+x ~/trb/tc
- chmod a+x ~/trb/tc/bin
- sudo chmod -R 755 ~/trb
- export ARCH=
- export CROSS_COMPILE=~/trb/tc/bin/arm-eabi-
- export KBUILD_BUILD_USER=""
- export KBUILD_BUILD_HOST=""
- make _defconfig
- make -j128
- cp ~/trb/arch/arm/boot/zImage ~/trb/lf
- cd ~/trb/lf
- zip -r9 TheRagingBeast_a6000-CIBuild.zip ~/trb/lf/*
- curl --upload-file ./TheRagingBeast_a6000-CIBuild.zip https://transfer.sh/TheRagingBeast_a6000-CIBuild.zip
- cd ~/trb/arch/arm/boot
- curl --upload-file ./zImage https://transfer.sh/zImage
- cd ~/trb/lf
- echo All Done
